DROP TABLE IF EXISTS pool_members CASCADE;
DROP TABLE IF EXISTS pools CASCADE;
DROP TABLE IF EXISTS bank_entries CASCADE;
DROP TABLE IF EXISTS ship_routes CASCADE;
DROP TABLE IF EXISTS ship_compliance CASCADE;
DROP TABLE IF EXISTS routes CASCADE;

-- ROUTES TABLE
CREATE TABLE routes (
  id SERIAL PRIMARY KEY,
  route_id TEXT NOT NULL UNIQUE,
  vessel_type TEXT NOT NULL,
  fuel_type TEXT NOT NULL,
  year INT NOT NULL,
  ghg_intensity NUMERIC NOT NULL,
  fuel_consumption NUMERIC NOT NULL,
  distance_km NUMERIC NOT NULL,
  total_emissions NUMERIC NOT NULL,
  is_baseline BOOLEAN DEFAULT FALSE
);

-- SHIP COMPLIANCE
CREATE TABLE ship_compliance (
  id SERIAL PRIMARY KEY,
  ship_id TEXT NOT NULL,
  year INT NOT NULL,
  cb_gco2eq NUMERIC NOT NULL DEFAULT 0,
  UNIQUE (ship_id, year)
);

-- BANK ENTRIES
CREATE TABLE bank_entries (
  id SERIAL PRIMARY KEY,
  ship_id TEXT NOT NULL,
  year INT NOT NULL,
  amount_gco2eq NUMERIC NOT NULL
);

-- POOLS
CREATE TABLE pools (
  id SERIAL PRIMARY KEY,
  year INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- POOL MEMBERS
CREATE TABLE pool_members (
  id SERIAL PRIMARY KEY,
  pool_id INT NOT NULL REFERENCES pools(id) ON DELETE CASCADE,
  ship_id TEXT NOT NULL,
  cb_before NUMERIC NOT NULL,
  cb_after NUMERIC NOT NULL
);

--SHIP ROUTES TABLE (THIS FIXES YOUR ERROR)
CREATE TABLE ship_routes (
  id SERIAL PRIMARY KEY,
  ship_id TEXT NOT NULL,
  route_id TEXT NOT NULL REFERENCES routes(route_id),
  year INT NOT NULL
);
